apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: obnoxious-boa-go
  janus-idp.io/tekton: obnoxious-boa-go
  backstage.io/kubernetes-id: obnoxious-boa-go
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: obnoxious-boa-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
